dataset_type: onthefly
model: !!python/name:ligmet.models.Model ''
model_config:
  decoder_args:
    binning_layer_args:
      dropout_rate: 0.1
      input_dim: 32
      num_layers: 5
      output_dim: 3
    prob_transform_args:
      attention:
        dropout_rate: 0.1
        embed_dim: 64
        input_dim: 32
        num_heads: 8
        num_layers: 1
        output_dim: 1
      linear:
        dropout_rate: 0.1
        input_dim: 32
        num_layers: 5
        output_dim: 1
    type_transform_args:
      attention:
        dropout_rate: 0.1
        embed_dim: 64
        input_dim: 32
        num_heads: 8
        num_layers: 1
        output_dim: 11
      linear:
        dropout_rate: 0.1
        input_dim: 32
        num_layers: 5
        output_dim: 11
    use_attention_prob: false
    use_attention_type: false
  encoder_args:
    dropout_rate: 0.1
    egnn_args:
      edge_feat_dim: 0
      hidden_dim: 256
      input_dim: 32
      num_layers: 5
      output_dim: 32
    hidden_dim: 256
    input_dim: 224
    output_dim: 32
onthefly:
  edge_dist_cutoff: 3.0
  pdb_dir: /home/qkrgangeun/LigMet/data/biolip/pdb
  pocket_dist: 6
  rf_model: /home/qkrgangeun/LigMet/data/biolip/rf/rf_param/example.param
  rf_threshold: 1.0
  topk: 16
preprocessed:
  edge_dist_cutoff: 3.0
  features_dir: /home/qkrgangeun/LigMet/data/biolip/DL/features
  pocket_dist: 6
  rf_result_dir: /home/qkrgangeun/LigMet/data/biolip/rf/results
  rf_threshold: 0.5
  topk: 16
train_data_file: /home/qkrgangeun/LigMet/code/text/biolip/train_pdbs.txt
train_loader_params:
  batch_size: 1
  num_workers: 1
  pin_memory: true
  shuffle: false
val_data_file: /home/qkrgangeun/LigMet/code/text/biolip/val_pdbs.txt
val_loader_params:
  batch_size: 1
  num_workers: 1
  pin_memory: true
  shuffle: false
